package formatter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/multigent/multigent/internal/ctxbuild"
)

// codexFormatter generates the file layout for OpenAI Codex.
//
// Codex loads AGENTS.md files from the Git root down to the current working
// directory, concatenating them with later files taking precedence. It has no
// native @import syntax and no skills mechanism, so we produce a single merged
// AGENTS.md that contains all layers in order, with skills inlined at the end.
//
// Skill files (scripts etc.) are copied to .multigent-skills/<name>/ and
// {{SKILL_DIR}} placeholders in prompts are replaced with the absolute path.
//
// Output structure inside outDir:
//
//	AGENTS.md                    ← all layers merged, skills inlined
//	.multigent-skills/<name>/   ← bundled skill files (scripts etc.)
type codexFormatter struct{}

func (f *codexFormatter) Format(mc *ctxbuild.MergedContext, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("codex: create output dir: %w", err)
	}

	// Deploy skill files first so we can resolve {{SKILL_DIR}} in prompts.
	resolved := resolveSkillsToDir(mc.Skills, outDir)

	content := buildAgentsMD(mc.Layers, resolved)
	path := filepath.Join(outDir, "AGENTS.md")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("codex: write AGENTS.md: %w", err)
	}
	return nil
}

// buildAgentsMD merges all context layers and skills into a single Markdown
// document suitable for Codex.
func buildAgentsMD(layers []ctxbuild.ContextLayer, skills []ctxbuild.SkillDef) string {
	var sb strings.Builder
	sb.WriteString("<!-- Generated by multigent. Do not edit manually. Run `multigent sync` to update. -->\n\n")

	for i, layer := range layers {
		if i > 0 {
			sb.WriteString("\n---\n\n")
		}
		sb.WriteString(fmt.Sprintf("<!-- [multigent] source: %s -->\n", layer.Source))
		sb.WriteString(strings.TrimSpace(layer.Content))
		sb.WriteString("\n")
	}

	if len(skills) > 0 {
		sb.WriteString("\n---\n\n")
		sb.WriteString("## Skills Reference\n\n")
		sb.WriteString("The following skills are available to you.\n\n")
		for _, sk := range skills {
			sb.WriteString(fmt.Sprintf("### %s\n\n", sk.Name))
			if sk.Description != "" {
				sb.WriteString(fmt.Sprintf("> %s\n\n", sk.Description))
			}
			if sk.Prompt != "" {
				sb.WriteString(strings.TrimSpace(sk.Prompt))
				sb.WriteString("\n\n")
			}
		}
	}

	return sb.String()
}
