package formatter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/multigent/multigent/internal/ctxbuild"
)

// cursorFormatter generates context files for Cursor Agent.
//
// Cursor reads rules from two locations (both are written):
//
//  1. .cursorrules          — legacy flat file, widely supported
//  2. .cursor/rules/*.mdc   — modern per-file rules (Cursor ≥ 0.43)
//
// Skills have no native Cursor mechanism, so they are inlined at the end
// of the rules content (same approach as Codex).
//
// Output structure inside outDir:
//
//	.cursorrules                    ← merged context (legacy format)
//	.cursor/
//	  rules/
//	    multigent.mdc               ← merged context (modern format)
type cursorFormatter struct{}

func (f *cursorFormatter) Format(mc *ctxbuild.MergedContext, outDir string) error {
	// Deploy skill files and resolve {{SKILL_DIR}} before rendering text.
	resolved := *mc
	resolved.Skills = resolveSkillsToDir(mc.Skills, outDir)
	mc = &resolved
	content := buildCursorRules(mc)

	// 1. .cursorrules (legacy — broadest compatibility)
	legacyPath := filepath.Join(outDir, ".cursorrules")
	if err := os.WriteFile(legacyPath, []byte(content), 0o644); err != nil {
		return fmt.Errorf("cursor: write .cursorrules: %w", err)
	}

	// 2. .cursor/rules/multigent.mdc (modern format)
	rulesDir := filepath.Join(outDir, ".cursor", "rules")
	if err := os.MkdirAll(rulesDir, 0o755); err != nil {
		return fmt.Errorf("cursor: create rules dir: %w", err)
	}
	mdcContent := buildCursorMDC(mc)
	mdcPath := filepath.Join(rulesDir, "multigent.mdc")
	if err := os.WriteFile(mdcPath, []byte(mdcContent), 0o644); err != nil {
		return fmt.Errorf("cursor: write multigent.mdc: %w", err)
	}

	return nil
}

// buildCursorRules produces the content for .cursorrules.
// This is plain Markdown; Cursor injects it as the system prompt.
func buildCursorRules(mc *ctxbuild.MergedContext) string {
	var sb strings.Builder
	sb.WriteString("<!-- Generated by multigent. Do not edit manually. Run `multigent sync` to update. -->\n\n")

	for i, layer := range mc.Layers {
		if i > 0 {
			sb.WriteString("\n---\n\n")
		}
		sb.WriteString(fmt.Sprintf("<!-- [multigent] source: %s -->\n", layer.Source))
		sb.WriteString(strings.TrimSpace(layer.Content))
		sb.WriteString("\n")
	}

	if len(mc.Skills) > 0 {
		sb.WriteString("\n---\n\n")
		sb.WriteString("## Skills Reference\n\n")
		for _, sk := range mc.Skills {
			sb.WriteString(fmt.Sprintf("### %s\n\n", sk.Name))
			if sk.Description != "" {
				sb.WriteString(fmt.Sprintf("> %s\n\n", sk.Description))
			}
			if sk.Prompt != "" {
				sb.WriteString(strings.TrimSpace(sk.Prompt))
				sb.WriteString("\n\n")
			}
		}
	}

	appendRuntimeConnectionsGuide(&sb)
	return sb.String()
}

// buildCursorMDC wraps the rules content in the .mdc frontmatter that the
// modern Cursor rules system expects. alwaysApply: true means the rules are
// injected into every conversation automatically.
func buildCursorMDC(mc *ctxbuild.MergedContext) string {
	var sb strings.Builder
	sb.WriteString("---\n")
	sb.WriteString("description: multigent context — auto-generated, do not edit\n")
	sb.WriteString("alwaysApply: true\n")
	sb.WriteString("---\n\n")
	sb.WriteString(buildCursorRules(mc))
	return sb.String()
}
