package formatter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/multigent/multigent/internal/ctxbuild"
)

// geminiFormatter generates context files for Google Gemini CLI.
//
// Gemini CLI reads GEMINI.md from the project directory (and ~/.gemini/GEMINI.md
// for global context). It also supports a skills system at .gemini/skills/ that
// mirrors Claude Code's .claude/skills/ structure.
//
// Output structure inside outDir:
//
//	GEMINI.md                    ← merged context (uses @import like Claude Code)
//	.multigent/
//	  context/
//	    agency.md
//	    role-<team>-<role>.md
//	    project-<project>.md
//	    wakeup.md              ← playbook (installed by project apply / sync)
//	  agent.yaml               ← agent metadata
//	  tasks.yaml              ← active task queue
//	  tasks_archive.yaml      ← archived tasks
//	  heartbeat.yaml          ← wakeup config
//	  crons.yaml              ← scheduled tasks
//	  messages.yaml           ← async messages
//	  runs/                   ← execution logs
//	  tasks/                  ← role workspace (from role setup)
//	  roadmap/                ← role workspace (from role setup)
//	  okr/                    ← role workspace (from role setup)
//	.gemini/
//	  skills/
//	    git/
//	      SKILL.md
type geminiFormatter struct{}

func (f *geminiFormatter) Format(mc *ctxbuild.MergedContext, outDir string) error {
	contextDir := filepath.Join(outDir, ".multigent", "context")
	if err := os.MkdirAll(contextDir, 0o755); err != nil {
		return fmt.Errorf("gemini: create context dir: %w", err)
	}

	var importLines []string
	for _, layer := range mc.Layers {
		filename := sourceToFilename(layer.Source) + ".md"
		path := filepath.Join(contextDir, filename)
		if err := os.WriteFile(path, []byte(layer.Content), 0o644); err != nil {
			return fmt.Errorf("gemini: write layer %q: %w", layer.Source, err)
		}
		importLines = append(importLines, fmt.Sprintf("@.multigent/context/%s", filename))
	}

	// Include wakeup routine if installed.
	if _, err := os.Stat(filepath.Join(contextDir, "wakeup.md")); err == nil {
		importLines = append(importLines, "@.multigent/context/wakeup.md")
	}

	// GEMINI.md supports the same @import syntax as CLAUDE.md
	geminiMD := buildGeminiMD(importLines)
	if err := os.WriteFile(filepath.Join(outDir, "GEMINI.md"), []byte(geminiMD), 0o644); err != nil {
		return fmt.Errorf("gemini: write GEMINI.md: %w", err)
	}

	// Skills → .gemini/skills/<name>/SKILL.md (+ any bundled files)
	for _, sk := range mc.Skills {
		skillDir := filepath.Join(outDir, ".gemini", "skills", sk.Name)
		if err := os.RemoveAll(skillDir); err != nil && !os.IsNotExist(err) {
			return fmt.Errorf("gemini: reset skill dir %q: %w", sk.Name, err)
		}
		if err := os.MkdirAll(skillDir, 0o755); err != nil {
			return fmt.Errorf("gemini: create skill dir %q: %w", sk.Name, err)
		}
		absSkillDir, err := deploySkillFiles(sk, skillDir)
		if err != nil {
			return fmt.Errorf("gemini: %w", err)
		}
		resolved := sk
		resolved.Prompt = resolveSkillDir(sk.Prompt, absSkillDir)
		skillMD := buildSkillMD(resolved)
		if err := os.WriteFile(filepath.Join(skillDir, "SKILL.md"), []byte(skillMD), 0o644); err != nil {
			return fmt.Errorf("gemini: write skill %q: %w", sk.Name, err)
		}
	}

	return nil
}

func buildGeminiMD(importLines []string) string {
	var sb strings.Builder
	sb.WriteString("<!-- Generated by multigent. Do not edit manually. Run `multigent sync` to update. -->\n\n")
	for _, line := range importLines {
		sb.WriteString(line)
		sb.WriteString("\n")
	}
	return sb.String()
}
