package formatter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/multigent/multigent/internal/ctxbuild"
)

// genericFormatter generates a plain context.md file for generic CLI agents.
// The user is responsible for passing its content to their agent via whatever
// mechanism that agent supports (--system-prompt, environment variable, etc.).
//
// Output structure inside outDir:
//
//	context.md    ← all layers merged, skills appended
type genericFormatter struct{}

func (f *genericFormatter) Format(mc *ctxbuild.MergedContext, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("generic: create output dir: %w", err)
	}

	content := buildContextMD(mc)
	path := filepath.Join(outDir, "context.md")
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("generic: write context.md: %w", err)
	}
	return nil
}

func buildContextMD(mc *ctxbuild.MergedContext) string {
	var sb strings.Builder
	sb.WriteString("<!-- Generated by multigent. Do not edit manually. Run `multigent sync` to update. -->\n\n")

	for i, layer := range mc.Layers {
		if i > 0 {
			sb.WriteString("\n---\n\n")
		}
		sb.WriteString(fmt.Sprintf("<!-- source: %s -->\n", layer.Source))
		sb.WriteString(strings.TrimSpace(layer.Content))
		sb.WriteString("\n")
	}

	if len(mc.Skills) > 0 {
		sb.WriteString("\n---\n\n")
		sb.WriteString("## Available Skills\n\n")
		for _, sk := range mc.Skills {
			sb.WriteString(fmt.Sprintf("### %s\n\n", sk.Name))
			if sk.Description != "" {
				sb.WriteString(fmt.Sprintf("%s\n\n", sk.Description))
			}
			if sk.Prompt != "" {
				sb.WriteString(strings.TrimSpace(sk.Prompt))
				sb.WriteString("\n\n")
			}
		}
	}

	return sb.String()
}
