package formatter

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/multigent/multigent/internal/ctxbuild"
)

// singleFileFormatter writes all context layers and skills into one Markdown
// file with a configurable name. Used by OpenCode (OPENCODE.md) and
// iFlow (IFLOW.md), which each use their own named instruction file but
// follow the same single-file convention as Codex.
type singleFileFormatter struct {
	filename string // e.g. "OPENCODE.md", "IFLOW.md"
}

func (f *singleFileFormatter) Format(mc *ctxbuild.MergedContext, outDir string) error {
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		return fmt.Errorf("%s: create output dir: %w", f.filename, err)
	}

	// Deploy skill files and resolve {{SKILL_DIR}} before rendering text.
	resolved := *mc
	resolved.Skills = resolveSkillsToDir(mc.Skills, outDir)
	mc = &resolved
	content := buildSingleFileMD(mc, f.filename)
	path := filepath.Join(outDir, f.filename)
	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("%s: write file: %w", f.filename, err)
	}
	return nil
}

func buildSingleFileMD(mc *ctxbuild.MergedContext, filename string) string {
	var sb strings.Builder
	sb.WriteString(fmt.Sprintf(
		"<!-- Generated by multigent. Do not edit manually. Run `multigent sync` to update. -->\n\n",
	))

	for i, layer := range mc.Layers {
		if i > 0 {
			sb.WriteString("\n---\n\n")
		}
		sb.WriteString(fmt.Sprintf("<!-- [multigent] source: %s -->\n", layer.Source))
		sb.WriteString(strings.TrimSpace(layer.Content))
		sb.WriteString("\n")
	}

	if len(mc.Skills) > 0 {
		sb.WriteString("\n---\n\n")
		sb.WriteString("## Skills Reference\n\n")
		sb.WriteString("The following skills are available to you.\n\n")
		for _, sk := range mc.Skills {
			sb.WriteString(fmt.Sprintf("### %s\n\n", sk.Name))
			if sk.Description != "" {
				sb.WriteString(fmt.Sprintf("> %s\n\n", sk.Description))
			}
			if sk.Prompt != "" {
				sb.WriteString(strings.TrimSpace(sk.Prompt))
				sb.WriteString("\n\n")
			}
		}
	}

	_ = filename // referenced in error messages via the struct field
	return sb.String()
}
