package db

func (db *SQLiteStore) migrate() error {
	stmts := []string{
		`CREATE TABLE IF NOT EXISTS workspaces (
	id TEXT PRIMARY KEY,
	name TEXT NOT NULL,
	slug TEXT NOT NULL,
	description TEXT NOT NULL DEFAULT '',
	root TEXT NOT NULL UNIQUE,
	created_by TEXT NOT NULL DEFAULT 'system',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	last_opened_at TEXT NOT NULL DEFAULT ''
)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_workspaces_slug ON workspaces(slug)`,
		`CREATE TABLE IF NOT EXISTS users (
	username TEXT PRIMARY KEY,
	email TEXT UNIQUE,
	display_name TEXT NOT NULL DEFAULT '',
	role TEXT NOT NULL DEFAULT 'member',
	avatar TEXT NOT NULL DEFAULT '',
	phone TEXT NOT NULL DEFAULT '',
	bio TEXT NOT NULL DEFAULT '',
	password_hash TEXT NOT NULL DEFAULT '',
	disabled INTEGER NOT NULL DEFAULT 0,
	created_at TEXT NOT NULL,
	projects_json TEXT NOT NULL DEFAULT '[]',
	linked_agents_json TEXT NOT NULL DEFAULT '[]',
	worker_grants_json TEXT NOT NULL DEFAULT '[]'
)`,
		`ALTER TABLE users ADD COLUMN projects_json TEXT NOT NULL DEFAULT '[]'`,
		`ALTER TABLE users ADD COLUMN linked_agents_json TEXT NOT NULL DEFAULT '[]'`,
		`ALTER TABLE users ADD COLUMN worker_grants_json TEXT NOT NULL DEFAULT '[]'`,
		`CREATE TABLE IF NOT EXISTS workspace_members (
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	username TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE,
	role TEXT NOT NULL DEFAULT 'member',
	created_at TEXT NOT NULL,
	PRIMARY KEY (workspace_id, username)
)`,
		`CREATE INDEX IF NOT EXISTS idx_workspace_members_username ON workspace_members(username)`,
		`CREATE TABLE IF NOT EXISTS settings (
	key TEXT PRIMARY KEY,
	value TEXT NOT NULL
)`,
		`CREATE TABLE IF NOT EXISTS invitations (
	token TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL DEFAULT '',
	email TEXT NOT NULL,
	role TEXT NOT NULL,
	display_name TEXT NOT NULL DEFAULT '',
	projects_json TEXT NOT NULL DEFAULT '[]',
	linked_agents_json TEXT NOT NULL DEFAULT '[]',
	invited_by TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL,
	created_at TEXT NOT NULL,
	expires_at TEXT NOT NULL,
	accepted_at TEXT NOT NULL DEFAULT ''
)`,
		`ALTER TABLE invitations ADD COLUMN workspace_id TEXT NOT NULL DEFAULT ''`,
		`CREATE INDEX IF NOT EXISTS idx_invitations_email_status ON invitations(email, status)`,
		`CREATE INDEX IF NOT EXISTS idx_invitations_workspace_status ON invitations(workspace_id, status)`,
		`CREATE TABLE IF NOT EXISTS kv_records (
	table_name TEXT NOT NULL,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	k1 TEXT NOT NULL DEFAULT '',
	k2 TEXT NOT NULL DEFAULT '',
	k3 TEXT NOT NULL DEFAULT '',
	payload TEXT NOT NULL,
	updated_at TEXT NOT NULL,
	PRIMARY KEY (table_name, workspace_id, k1, k2, k3)
)`,
		`CREATE INDEX IF NOT EXISTS idx_kv_records_lookup ON kv_records(table_name, workspace_id, k1, k2)`,
		`CREATE TABLE IF NOT EXISTS audit_events (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL DEFAULT '',
	actor_type TEXT NOT NULL,
	actor_id TEXT NOT NULL,
	action TEXT NOT NULL,
	resource_type TEXT NOT NULL,
	resource_id TEXT NOT NULL,
	summary TEXT NOT NULL DEFAULT '',
	before_json TEXT NOT NULL DEFAULT '',
	after_json TEXT NOT NULL DEFAULT '',
	ip TEXT NOT NULL DEFAULT '',
	user_agent TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL
)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_events_workspace_time ON audit_events(workspace_id, created_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_audit_events_resource ON audit_events(resource_type, resource_id, created_at DESC)`,
		`CREATE TABLE IF NOT EXISTS connector_providers (
	provider TEXT PRIMARY KEY,
	display_name TEXT NOT NULL,
	auth_types_json TEXT NOT NULL DEFAULT '[]',
	catalog_json TEXT NOT NULL DEFAULT '{}',
	enabled INTEGER NOT NULL DEFAULT 1,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT ''
)`,
		`CREATE INDEX IF NOT EXISTS idx_connector_providers_enabled ON connector_providers(enabled, provider)`,
		`CREATE TABLE IF NOT EXISTS oauth_client_configs (
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	provider TEXT NOT NULL,
	client_id TEXT NOT NULL,
	secret_ciphertext TEXT NOT NULL DEFAULT '',
	nonce TEXT NOT NULL DEFAULT '',
	key_version TEXT NOT NULL DEFAULT '',
	extra_json TEXT NOT NULL DEFAULT '{}',
	created_by TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	PRIMARY KEY (workspace_id, provider)
)`,
		`CREATE INDEX IF NOT EXISTS idx_oauth_client_configs_workspace ON oauth_client_configs(workspace_id, provider)`,
		`CREATE TABLE IF NOT EXISTS connections (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	provider TEXT NOT NULL,
	connection_name TEXT NOT NULL DEFAULT 'default',
	owner_type TEXT NOT NULL,
	owner_id TEXT NOT NULL,
	auth_type TEXT NOT NULL,
	status TEXT NOT NULL DEFAULT 'active',
	profile_json TEXT NOT NULL DEFAULT '{}',
	created_by TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	last_used_at TEXT NOT NULL DEFAULT '',
	UNIQUE(workspace_id, provider, owner_type, owner_id, connection_name)
)`,
		`CREATE INDEX IF NOT EXISTS idx_connections_workspace_provider ON connections(workspace_id, provider)`,
		`CREATE INDEX IF NOT EXISTS idx_connections_owner ON connections(workspace_id, owner_type, owner_id)`,
		`CREATE TABLE IF NOT EXISTS connection_secrets (
	connection_id TEXT PRIMARY KEY REFERENCES connections(id) ON DELETE CASCADE,
	ciphertext TEXT NOT NULL,
	nonce TEXT NOT NULL DEFAULT '',
	key_version TEXT NOT NULL DEFAULT '',
	updated_at TEXT NOT NULL
)`,
		`CREATE TABLE IF NOT EXISTS connection_grants (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	connection_id TEXT NOT NULL REFERENCES connections(id) ON DELETE CASCADE,
	target_type TEXT NOT NULL,
	target_id TEXT NOT NULL,
	created_by TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	UNIQUE(connection_id, target_type, target_id)
)`,
		`CREATE INDEX IF NOT EXISTS idx_connection_grants_target ON connection_grants(workspace_id, target_type, target_id)`,
		`CREATE TABLE IF NOT EXISTS agent_tool_bindings (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	agent_worker_id TEXT NOT NULL DEFAULT '',
	project_id TEXT NOT NULL,
	agent_id TEXT NOT NULL,
	connection_id TEXT NOT NULL REFERENCES connections(id) ON DELETE CASCADE,
	provider TEXT NOT NULL,
	adapter_type TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL DEFAULT 'enabled',
	config_json TEXT NOT NULL DEFAULT '{}',
	created_by TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	UNIQUE(workspace_id, project_id, agent_id, connection_id)
)`,
		`ALTER TABLE agent_tool_bindings ADD COLUMN agent_worker_id TEXT NOT NULL DEFAULT ''`,
		`CREATE INDEX IF NOT EXISTS idx_agent_tool_bindings_agent ON agent_tool_bindings(workspace_id, project_id, agent_id, status)`,
		`CREATE INDEX IF NOT EXISTS idx_agent_tool_bindings_worker ON agent_tool_bindings(workspace_id, agent_worker_id, status)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_agent_tool_bindings_worker_connection ON agent_tool_bindings(workspace_id, agent_worker_id, connection_id) WHERE agent_worker_id != ''`,
		`CREATE INDEX IF NOT EXISTS idx_agent_tool_bindings_connection ON agent_tool_bindings(connection_id)`,
		`CREATE TABLE IF NOT EXISTS agent_workers (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	name TEXT NOT NULL,
	display_name TEXT NOT NULL DEFAULT '',
	description TEXT NOT NULL DEFAULT '',
	profile_prompt TEXT NOT NULL DEFAULT '',
		avatar TEXT NOT NULL DEFAULT '',
		team TEXT NOT NULL DEFAULT '',
		role TEXT NOT NULL DEFAULT '',
		status TEXT NOT NULL DEFAULT 'active',
		model TEXT NOT NULL DEFAULT '',
		runtime_model TEXT NOT NULL DEFAULT '',
		default_model_account_id TEXT NOT NULL DEFAULT '',
	default_runtime_node_id TEXT NOT NULL DEFAULT '',
	default_runtime_mode TEXT NOT NULL DEFAULT '',
	schedule_json TEXT NOT NULL DEFAULT '{}',
	attention_policy_json TEXT NOT NULL DEFAULT '{}',
		memory_policy_json TEXT NOT NULL DEFAULT '{}',
		skills_json TEXT NOT NULL DEFAULT '[]',
		runtime_config_json TEXT NOT NULL DEFAULT '{}',
		primary_session_id TEXT NOT NULL DEFAULT '',
		created_at TEXT NOT NULL,
		updated_at TEXT NOT NULL DEFAULT '',
		UNIQUE(workspace_id, name)
		)`,
		`ALTER TABLE agent_workers ADD COLUMN model TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE agent_workers ADD COLUMN runtime_model TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE agent_workers ADD COLUMN runtime_config_json TEXT NOT NULL DEFAULT '{}'`,
		`ALTER TABLE agent_workers ADD COLUMN team TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE agent_workers ADD COLUMN role TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE agent_workers ADD COLUMN profile_prompt TEXT NOT NULL DEFAULT ''`,
		`CREATE INDEX IF NOT EXISTS idx_agent_workers_workspace_status ON agent_workers(workspace_id, status, name)`,
		`CREATE TABLE IF NOT EXISTS agent_sessions (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	agent_worker_id TEXT NOT NULL REFERENCES agent_workers(id) ON DELETE CASCADE,
	session_kind TEXT NOT NULL DEFAULT 'fork',
	parent_session_id TEXT NOT NULL DEFAULT '',
	project_id TEXT NOT NULL DEFAULT '',
	project_membership_id TEXT NOT NULL DEFAULT '',
	task_id TEXT NOT NULL DEFAULT '',
	workflow_instance_id TEXT NOT NULL DEFAULT '',
	title TEXT NOT NULL DEFAULT '',
	purpose TEXT NOT NULL DEFAULT '',
	initial_prompt TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL DEFAULT 'pending',
	runtime_provider TEXT NOT NULL DEFAULT '',
	runtime_session_id TEXT NOT NULL DEFAULT '',
	fork_mode TEXT NOT NULL DEFAULT 'fresh_with_context',
	permission_policy TEXT NOT NULL DEFAULT 'inherit',
	capabilities_json TEXT NOT NULL DEFAULT '{}',
	result_summary TEXT NOT NULL DEFAULT '',
	result_refs_json TEXT NOT NULL DEFAULT '{}',
	created_by_run_id TEXT NOT NULL DEFAULT '',
	last_run_id TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	last_activity_at TEXT NOT NULL DEFAULT '',
	completed_at TEXT NOT NULL DEFAULT ''
)`,
		`ALTER TABLE agent_sessions ADD COLUMN initial_prompt TEXT NOT NULL DEFAULT ''`,
		`CREATE INDEX IF NOT EXISTS idx_agent_sessions_worker_status ON agent_sessions(workspace_id, agent_worker_id, session_kind, status, updated_at DESC)`,
		`CREATE INDEX IF NOT EXISTS idx_agent_sessions_project_task ON agent_sessions(workspace_id, project_id, task_id, status)`,
		`CREATE INDEX IF NOT EXISTS idx_agent_sessions_parent ON agent_sessions(workspace_id, parent_session_id)`,
		`CREATE TABLE IF NOT EXISTS project_memberships (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	project_id TEXT NOT NULL,
	member_type TEXT NOT NULL,
	member_id TEXT NOT NULL,
	role TEXT NOT NULL DEFAULT '',
	title TEXT NOT NULL DEFAULT '',
	prompt TEXT NOT NULL DEFAULT '',
	permissions_json TEXT NOT NULL DEFAULT '[]',
	auto_pick_tasks INTEGER NOT NULL DEFAULT 1,
	attention_enabled INTEGER NOT NULL DEFAULT 1,
	priority_weight REAL NOT NULL DEFAULT 1.0,
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	UNIQUE(workspace_id, project_id, member_type, member_id)
)`,
		`CREATE INDEX IF NOT EXISTS idx_project_memberships_project ON project_memberships(workspace_id, project_id, member_type)`,
		`CREATE INDEX IF NOT EXISTS idx_project_memberships_member ON project_memberships(workspace_id, member_type, member_id)`,
		`CREATE TABLE IF NOT EXISTS attention_signals (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	agent_worker_id TEXT NOT NULL REFERENCES agent_workers(id) ON DELETE CASCADE,
	dedupe_key TEXT NOT NULL,
	source_kind TEXT NOT NULL,
	source_id TEXT NOT NULL DEFAULT '',
	source_channel TEXT NOT NULL DEFAULT '',
	reason TEXT NOT NULL,
	priority TEXT NOT NULL DEFAULT 'normal',
	actor_type TEXT NOT NULL DEFAULT '',
	actor_id TEXT NOT NULL DEFAULT '',
	summary TEXT NOT NULL DEFAULT '',
	refs_json TEXT NOT NULL DEFAULT '{}',
	payload_json TEXT NOT NULL DEFAULT '{}',
	result_ref TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL DEFAULT 'pending',
	created_at TEXT NOT NULL,
	expires_at TEXT NOT NULL DEFAULT '',
	seen_at TEXT NOT NULL DEFAULT '',
	handling_at TEXT NOT NULL DEFAULT '',
	handled_at TEXT NOT NULL DEFAULT '',
	UNIQUE(workspace_id, agent_worker_id, dedupe_key)
)`,
		`CREATE INDEX IF NOT EXISTS idx_attention_signals_agent_status ON attention_signals(workspace_id, agent_worker_id, status, created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_attention_signals_source ON attention_signals(workspace_id, source_kind, source_id)`,
		`CREATE TABLE IF NOT EXISTS attention_cursors (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	agent_worker_id TEXT NOT NULL REFERENCES agent_workers(id) ON DELETE CASCADE,
	source_kind TEXT NOT NULL,
	source_channel TEXT NOT NULL,
	cursor TEXT NOT NULL DEFAULT '',
	seen_until TEXT NOT NULL DEFAULT '',
	updated_at TEXT NOT NULL,
	UNIQUE(workspace_id, agent_worker_id, source_kind, source_channel)
)`,
		`CREATE INDEX IF NOT EXISTS idx_attention_cursors_agent_source ON attention_cursors(workspace_id, agent_worker_id, source_kind)`,
		`CREATE TABLE IF NOT EXISTS agent_channel_bindings (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	project_id TEXT NOT NULL,
	agent_id TEXT NOT NULL,
	provider TEXT NOT NULL,
	connection_id TEXT NOT NULL REFERENCES connections(id) ON DELETE CASCADE,
	external_bot_id TEXT NOT NULL DEFAULT '',
	external_chat_id TEXT NOT NULL DEFAULT '',
	external_owner_id TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL DEFAULT 'connected',
	metadata_json TEXT NOT NULL DEFAULT '{}',
	created_by TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	last_activity_at TEXT NOT NULL DEFAULT '',
	UNIQUE(workspace_id, project_id, agent_id, provider)
)`,
		`ALTER TABLE agent_channel_bindings ADD COLUMN agent_worker_id TEXT NOT NULL DEFAULT ''`,
		`CREATE INDEX IF NOT EXISTS idx_agent_channel_bindings_agent ON agent_channel_bindings(workspace_id, project_id, agent_id)`,
		`CREATE INDEX IF NOT EXISTS idx_agent_channel_bindings_worker ON agent_channel_bindings(workspace_id, agent_worker_id, provider)`,
		`CREATE INDEX IF NOT EXISTS idx_agent_channel_bindings_connection ON agent_channel_bindings(connection_id)`,
		`CREATE TABLE IF NOT EXISTS external_identities (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	provider TEXT NOT NULL,
	external_user_id TEXT NOT NULL,
	user_id TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE,
	metadata_json TEXT NOT NULL DEFAULT '{}',
	created_by TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	UNIQUE(workspace_id, provider, external_user_id)
)`,
		`CREATE INDEX IF NOT EXISTS idx_external_identities_user ON external_identities(workspace_id, user_id)`,
		`CREATE TABLE IF NOT EXISTS user_channel_identities (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	user_id TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE,
	channel_binding_id TEXT NOT NULL REFERENCES agent_channel_bindings(id) ON DELETE CASCADE,
	provider TEXT NOT NULL,
	external_user_id TEXT NOT NULL,
	external_chat_id TEXT NOT NULL DEFAULT '',
	metadata_json TEXT NOT NULL DEFAULT '{}',
	created_by TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	UNIQUE(workspace_id, channel_binding_id, external_user_id),
	UNIQUE(workspace_id, channel_binding_id, user_id)
)`,
		`CREATE INDEX IF NOT EXISTS idx_user_channel_identities_user ON user_channel_identities(workspace_id, user_id)`,
		`CREATE INDEX IF NOT EXISTS idx_user_channel_identities_external ON user_channel_identities(workspace_id, provider, external_user_id)`,
		`CREATE TABLE IF NOT EXISTS agent_channel_targets (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	channel_binding_id TEXT NOT NULL REFERENCES agent_channel_bindings(id) ON DELETE CASCADE,
	provider TEXT NOT NULL,
	target_type TEXT NOT NULL,
	display_name TEXT NOT NULL DEFAULT '',
	external_user_id TEXT NOT NULL DEFAULT '',
	external_chat_id TEXT NOT NULL DEFAULT '',
	metadata_json TEXT NOT NULL DEFAULT '{}',
	created_by TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	last_activity_at TEXT NOT NULL DEFAULT '',
	UNIQUE(workspace_id, channel_binding_id, target_type, external_chat_id)
)`,
		`CREATE INDEX IF NOT EXISTS idx_agent_channel_targets_channel ON agent_channel_targets(workspace_id, channel_binding_id, target_type)`,
		`CREATE INDEX IF NOT EXISTS idx_agent_channel_targets_provider ON agent_channel_targets(workspace_id, provider, target_type)`,
		`CREATE TABLE IF NOT EXISTS agent_channel_bind_codes (
	code TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	channel_binding_id TEXT NOT NULL REFERENCES agent_channel_bindings(id) ON DELETE CASCADE,
	user_id TEXT NOT NULL REFERENCES users(username) ON DELETE CASCADE,
	target_type TEXT NOT NULL DEFAULT 'user',
	target_name TEXT NOT NULL DEFAULT '',
	expires_at TEXT NOT NULL,
	used_at TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL
)`,
		`ALTER TABLE agent_channel_bind_codes ADD COLUMN target_type TEXT NOT NULL DEFAULT 'user'`,
		`ALTER TABLE agent_channel_bind_codes ADD COLUMN target_name TEXT NOT NULL DEFAULT ''`,
		`CREATE INDEX IF NOT EXISTS idx_agent_channel_bind_codes_channel ON agent_channel_bind_codes(workspace_id, channel_binding_id, user_id, expires_at)`,
		`CREATE TABLE IF NOT EXISTS interactive_sessions (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	agent_worker_id TEXT NOT NULL DEFAULT '',
	project_id TEXT NOT NULL,
	agent_id TEXT NOT NULL,
	source_kind TEXT NOT NULL,
	source_channel TEXT NOT NULL DEFAULT '',
	actor_type TEXT NOT NULL DEFAULT '',
	actor_id TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL DEFAULT 'active',
	lock_reason TEXT NOT NULL DEFAULT 'interactive',
	runtime_session_id TEXT NOT NULL DEFAULT '',
	current_run_id TEXT NOT NULL DEFAULT '',
	human_intervened INTEGER NOT NULL DEFAULT 0,
	metadata_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	last_activity_at TEXT NOT NULL DEFAULT '',
	completed_at TEXT NOT NULL DEFAULT ''
)`,
		`ALTER TABLE interactive_sessions ADD COLUMN agent_worker_id TEXT NOT NULL DEFAULT ''`,
		`CREATE INDEX IF NOT EXISTS idx_interactive_sessions_agent ON interactive_sessions(workspace_id, project_id, agent_id, status)`,
		`CREATE INDEX IF NOT EXISTS idx_interactive_sessions_worker ON interactive_sessions(workspace_id, agent_worker_id, status)`,
		`DROP INDEX IF EXISTS idx_interactive_sessions_one_active_agent`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_interactive_sessions_one_active_source ON interactive_sessions(workspace_id, project_id, agent_id, source_kind, source_channel, actor_id) WHERE status IN ('active', 'waiting_input')`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_interactive_sessions_one_active_worker_source ON interactive_sessions(workspace_id, agent_worker_id, source_kind, source_channel, actor_id) WHERE agent_worker_id != '' AND status IN ('active', 'waiting_input')`,
		`CREATE TABLE IF NOT EXISTS interaction_events (
	id TEXT PRIMARY KEY,
	session_id TEXT NOT NULL REFERENCES interactive_sessions(id) ON DELETE CASCADE,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	actor_type TEXT NOT NULL,
	actor_id TEXT NOT NULL,
	channel TEXT NOT NULL DEFAULT '',
	event_type TEXT NOT NULL,
	content TEXT NOT NULL DEFAULT '',
	metadata_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL
)`,
		`CREATE INDEX IF NOT EXISTS idx_interaction_events_session_time ON interaction_events(session_id, created_at ASC)`,
		`CREATE INDEX IF NOT EXISTS idx_interaction_events_workspace_time ON interaction_events(workspace_id, created_at DESC)`,
		`CREATE TABLE IF NOT EXISTS interaction_requests (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	agent_worker_id TEXT NOT NULL DEFAULT '',
	project_id TEXT NOT NULL,
	agent_id TEXT NOT NULL,
	channel_binding_id TEXT NOT NULL DEFAULT '',
	provider TEXT NOT NULL DEFAULT '',
	recipient TEXT NOT NULL DEFAULT '',
	target_type TEXT NOT NULL DEFAULT '',
	target_user_id TEXT NOT NULL DEFAULT '',
	target_chat_id TEXT NOT NULL DEFAULT '',
	title TEXT NOT NULL DEFAULT '',
	body TEXT NOT NULL DEFAULT '',
	schema_json TEXT NOT NULL DEFAULT '{}',
	context_json TEXT NOT NULL DEFAULT '{}',
	handler_type TEXT NOT NULL DEFAULT 'agent_event',
	status TEXT NOT NULL DEFAULT 'active',
	created_by TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	expires_at TEXT NOT NULL DEFAULT '',
	submitted_at TEXT NOT NULL DEFAULT '',
	submitted_by TEXT NOT NULL DEFAULT '',
	submission_json TEXT NOT NULL DEFAULT ''
)`,
		`ALTER TABLE interaction_requests ADD COLUMN agent_worker_id TEXT NOT NULL DEFAULT ''`,
		`CREATE INDEX IF NOT EXISTS idx_interaction_requests_agent ON interaction_requests(workspace_id, project_id, agent_id, status)`,
		`CREATE INDEX IF NOT EXISTS idx_interaction_requests_worker ON interaction_requests(workspace_id, agent_worker_id, status)`,
		`CREATE INDEX IF NOT EXISTS idx_interaction_requests_channel ON interaction_requests(workspace_id, channel_binding_id, status)`,
		`CREATE TABLE IF NOT EXISTS model_providers (
	id TEXT NOT NULL,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	owner_type TEXT NOT NULL DEFAULT 'workspace',
	owner_id TEXT NOT NULL DEFAULT '',
	name TEXT NOT NULL,
	type TEXT NOT NULL,
	base_url TEXT NOT NULL DEFAULT '',
	api_key TEXT NOT NULL DEFAULT '',
	model TEXT NOT NULL DEFAULT '',
	models_json TEXT NOT NULL DEFAULT '[]',
	env_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT '',
	PRIMARY KEY (workspace_id, id)
)`,
		`ALTER TABLE model_providers ADD COLUMN owner_type TEXT NOT NULL DEFAULT 'workspace'`,
		`ALTER TABLE model_providers ADD COLUMN owner_id TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE model_providers ADD COLUMN models_json TEXT NOT NULL DEFAULT '[]'`,
		`UPDATE model_providers SET owner_id = workspace_id WHERE owner_type = 'workspace' AND owner_id = ''`,
		`CREATE INDEX IF NOT EXISTS idx_model_providers_workspace ON model_providers(workspace_id, name)`,
		`CREATE INDEX IF NOT EXISTS idx_model_providers_owner ON model_providers(workspace_id, owner_type, owner_id)`,
		`CREATE TABLE IF NOT EXISTS runtime_nodes (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	name TEXT NOT NULL,
	kind TEXT NOT NULL,
	status TEXT NOT NULL,
	os TEXT NOT NULL DEFAULT '',
	arch TEXT NOT NULL DEFAULT '',
	hostname TEXT NOT NULL DEFAULT '',
	version TEXT NOT NULL DEFAULT '',
	capabilities_json TEXT NOT NULL DEFAULT '{}',
	policy_json TEXT NOT NULL DEFAULT '{}',
	last_seen_at TEXT NOT NULL DEFAULT '',
	last_error TEXT NOT NULL DEFAULT '',
	created_by_user_id TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT ''
)`,
		`CREATE INDEX IF NOT EXISTS idx_runtime_nodes_workspace ON runtime_nodes(workspace_id, status, name)`,
		`CREATE TABLE IF NOT EXISTS runtime_node_tokens (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	runtime_node_id TEXT NOT NULL REFERENCES runtime_nodes(id) ON DELETE CASCADE,
	token_hash TEXT NOT NULL UNIQUE,
	name TEXT NOT NULL DEFAULT '',
	scopes_json TEXT NOT NULL DEFAULT '[]',
	expires_at TEXT NOT NULL DEFAULT '',
	revoked_at TEXT NOT NULL DEFAULT '',
	created_by TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL
)`,
		`CREATE INDEX IF NOT EXISTS idx_runtime_node_tokens_node ON runtime_node_tokens(workspace_id, runtime_node_id, revoked_at)`,
		`CREATE TABLE IF NOT EXISTS runtime_runs (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	agent_worker_id TEXT NOT NULL DEFAULT '',
	project_membership_id TEXT NOT NULL DEFAULT '',
	project_id TEXT NOT NULL DEFAULT '',
	agent_id TEXT NOT NULL DEFAULT '',
	task_id TEXT NOT NULL DEFAULT '',
	workflow_instance_id TEXT NOT NULL DEFAULT '',
	workflow_step_id TEXT NOT NULL DEFAULT '',
	fork_session_id TEXT NOT NULL DEFAULT '',
	desired_runtime_node_id TEXT NOT NULL DEFAULT '',
	runtime_node_id TEXT NOT NULL DEFAULT '',
	status TEXT NOT NULL,
	priority INTEGER NOT NULL DEFAULT 2,
	spec_json TEXT NOT NULL DEFAULT '{}',
	result_json TEXT NOT NULL DEFAULT '{}',
	lease_expires_at TEXT NOT NULL DEFAULT '',
	claimed_at TEXT NOT NULL DEFAULT '',
	started_at TEXT NOT NULL DEFAULT '',
	finished_at TEXT NOT NULL DEFAULT '',
	error_code TEXT NOT NULL DEFAULT '',
	error_message TEXT NOT NULL DEFAULT '',
	created_at TEXT NOT NULL,
	updated_at TEXT NOT NULL DEFAULT ''
)`,
		`ALTER TABLE runtime_runs ADD COLUMN agent_worker_id TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE runtime_runs ADD COLUMN project_membership_id TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE runtime_runs ADD COLUMN fork_session_id TEXT NOT NULL DEFAULT ''`,
		`ALTER TABLE runtime_runs ADD COLUMN desired_runtime_node_id TEXT NOT NULL DEFAULT ''`,
		`CREATE INDEX IF NOT EXISTS idx_runtime_runs_queue ON runtime_runs(workspace_id, status, priority, created_at)`,
		`CREATE INDEX IF NOT EXISTS idx_runtime_runs_desired_node ON runtime_runs(workspace_id, desired_runtime_node_id, status)`,
		`CREATE INDEX IF NOT EXISTS idx_runtime_runs_node ON runtime_runs(workspace_id, runtime_node_id, status)`,
		`CREATE INDEX IF NOT EXISTS idx_runtime_runs_agent ON runtime_runs(workspace_id, project_id, agent_id, status)`,
		`CREATE INDEX IF NOT EXISTS idx_runtime_runs_worker ON runtime_runs(workspace_id, agent_worker_id, status)`,
		`CREATE INDEX IF NOT EXISTS idx_runtime_runs_fork_session ON runtime_runs(workspace_id, fork_session_id, status)`,
		`CREATE TABLE IF NOT EXISTS runtime_events (
	id TEXT PRIMARY KEY,
	workspace_id TEXT NOT NULL REFERENCES workspaces(id) ON DELETE CASCADE,
	run_id TEXT NOT NULL REFERENCES runtime_runs(id) ON DELETE CASCADE,
	sequence INTEGER NOT NULL,
	type TEXT NOT NULL,
	payload_json TEXT NOT NULL DEFAULT '{}',
	created_at TEXT NOT NULL
)`,
		`CREATE UNIQUE INDEX IF NOT EXISTS idx_runtime_events_run_sequence ON runtime_events(workspace_id, run_id, sequence)`,
	}
	for _, stmt := range stmts {
		if _, err := db.sql.Exec(stmt); err != nil {
			if len(stmt) > 5 && stmt[:5] == "ALTER" {
				continue
			}
			return err
		}
	}
	return nil
}
